version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: dockerMongoAdmin
            MONGO_INITDB_ROOT_PASSWORD: dockerMongoPassword
            MONGO_INITDB_DATABASE: dockerdb
        ports:
            - 27017:27017
        volumes:
            - .docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro