### Отправка сообщения в топик
POST localhost:9090/push/test
Content-Type: application/json
db-key: 12356

{
  "rr": 999,
  "value": "content"
}

### Изменение сообщения в топике
PATCH localhost:9090/push/test
Content-Type: application/json
db-key: 12356

{
  "id": "1113115156",
  "rr": 999,
  "value": "content"
}

### Поиск в топике
POST localhost:9090/find/test
Content-Type: application/json
db-key: 12356

{
  "id": "1113115156"
}

### Список всего в топике
GET localhost:9090/list/test
Content-Type: application/json
db-key: 123
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Access-Control-Request-Headers: access-control-allow-origin,content-type,db-key
Access-Control-Request-Method: GET
Cache-Control: max-age=0
Connection: keep-alive
Host: localhost:9090
Origin: http://localhost:3000
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Ag

### OPTIONS
OPTIONS localhost:9090/list/test
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Access-Control-Request-Headers: access-control-allow-origin,content-type,db-key
Access-Control-Request-Method: GET
Cache-Control: max-age=0
Connection: keep-alive
Host: localhost:9090
Origin: http://localhost:3000
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Ag



### Авторизация в админке
POST localhost:9090/admin/auth
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "test"
}

### Admin users
GET http://localhost:9090/admin/users?_end=10&_order=ASC&_sort=id&_start=0
Accept: */*
Authorization: Bearer 123
